before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  binary: toggl
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w -X github.com/sachaos/toggl.version={{.Version}}
archives:
- name_template: >-
    {{- .ProjectName }}_
    {{- .Version }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- repository:
    owner: sachaos
    name: homebrew-tap
  directory: Formula
  homepage: https://github.com/sachaos/toggl
  description: Toggl CLI client
  skip_upload: auto
  test: |
    system "#{bin}/toggl", "--version"
